#!/bin/bash
CWD=`pwd`
TTY=`ls -1 /dev/ttyACM*`
echo loading $1 to $TTY

RET=1
while [ $RET -eq 1 ]
do
#luatool -p $TTY --delay 0.8 -f $1
echo luatool -p $TTY -f $CWD/$1
~/projects/esp/ftl/luatool -p $TTY -f $CWD/$1
RET=$?
echo exit $RET
done

